Fix versioning script

diff --git a/rel b/rel
--- a/rel
+++ b/rel
@@ -6,14 +6,22 @@ if [ ! "$1" ]; then
   exit 1
 fi
 
+VERSION=$1
+
+if ! echo $VERSION | egrep -q '^[0-9.]+$'; then
+  echo 'Invalid version'
+  exit 1
+fi
+
 if ! git diff --quiet; then
   echo "Not clean"
   exit 1
 fi
 
-echo "__version__ = '$1'" > piir/version.py
+
+echo "__version__ = '$VERSION'" > piir/version.py
 
 python3 setup.py test || exit 1
 
-git commit piir/version.py -m v$1
-git tag v$1
+git commit piir/version.py -m v$VERSION
+git tag v$VERSION
